apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-env
  labels:
    app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
data:
  NODE_ENV: production
  {{ with .Values.database -}}
  DATABASE_HOST: {{ .host }}
  DATABASE_PORT: {{ .port | quote }}
  {{- end }}
