apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-1
  labels:
    app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-1
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
        app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-1
    spec:
      containers:
      - name: {{ include "nodejs-demoapp.app_name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
          limits:
            {{ with .Values.resourceLimits -}}
            memory: {{.memory}}
            cpu: {{.cpu}}
            {{- end }}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ include "nodejs-demoapp.app_name" . }}-env
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "nodejs-demoapp.app_name" . }}-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "nodejs-demoapp.app_name" . }}-secret
              key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-2
  labels:
    app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-2
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
        app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-2
    spec:
      containers:
      - name: {{ include "nodejs-demoapp.app_name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
          limits:
            {{ with .Values.resourceLimits -}}
            memory: {{.memory}}
            cpu: {{.cpu}}
            {{- end }}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ include "nodejs-demoapp.app_name" . }}-env
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "nodejs-demoapp.app_name" . }}-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "nodejs-demoapp.app_name" . }}-secret
              key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-3
  labels:
    app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-3
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-3
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
        app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-3
    spec:
      containers:
      - name: {{ include "nodejs-demoapp.app_name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
          limits:
            {{ with .Values.resourceLimits -}}
            memory: {{.memory}}
            cpu: {{.cpu}}
            {{- end }}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ include "nodejs-demoapp.app_name" . }}-env
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "nodejs-demoapp.app_name" . }}-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "nodejs-demoapp.app_name" . }}-secret
              key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-4
  labels:
    app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-4
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-4
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
        app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-4
    spec:
      containers:
      - name: {{ include "nodejs-demoapp.app_name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
          limits:
            {{ with .Values.resourceLimits -}}
            memory: {{.memory}}
            cpu: {{.cpu}}
            {{- end }}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ include "nodejs-demoapp.app_name" . }}-env
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "nodejs-demoapp.app_name" . }}-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "nodejs-demoapp.app_name" . }}-secret
              key: password
