{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
spec:
  ingressClassName: nginx
  rules:
  - host: app1.{{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "nodejs-demoapp.app_name" . }}-1
            port:
              number: 80
  - host: app2.{{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "nodejs-demoapp.app_name" . }}-2
            port:
              number: 80
  - host: app3.{{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "nodejs-demoapp.app_name" . }}-3
            port:
              number: 80
  - host: app4.{{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "nodejs-demoapp.app_name" . }}-4
            port:
              number: 80
{{- end -}}
