apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-secret
data:
  {{ with .Values.secret.database -}}
  username: {{ .username | b64enc }}
  password: {{ .password | b64enc }}
  {{- end }}

