apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-1
  labels:
    app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-1
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-1
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-2
  labels:
    app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-2
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-2
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-3
  labels:
    app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-3
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-3
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-demoapp.app_name" . }}-4
  labels:
    app.kubernetes.io/name: {{ include "nodejs-demoapp.app_name" . }}
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-4
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ include "nodejs-demoapp.app_name" . }}-4
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 80
